### ISSUE TITLE
OrderItems.js - better naming

### ISSUE THREAD

**Issue by pedanticantic** [dignat/fastFood#25]
All the getter methods don’t need the “OrderItem” text in the middle. Eg, it should be getId(), getName(), etc. The context will tell you what’s going on, eg $scope.myOrderItem.getName()

In fact, you only need an id and a reference to the menu item. You don’t need a copy of the name, type, etc.

Also, the class name should be singular - “OrderItem”

**Comment by dignat** [comment]
done
