### ISSUE TITLE
Appearance could be improved

### ISSUE THREAD

**Issue by pedanticantic** [dignat/fastFood#6]
There a no gaps around Order & Cancel buttons and message, and between the item being added and the qty.
A little bit CSS would go a long way!

**Comment by dignat** [comment]
Agree will style it.

**Comment by pedanticantic** [comment]
Hi Denise, just a piece of advice: don't close issues until *after* you have done the work :-)

**Comment by dignat** [comment]
Hi Glenn,
I was going through the issues and reading the comments. Did not intend to close the issue.
Thanks for the advice :)

**Comment by pedanticantic** [comment]
Ah, okay. No problem :-)
